### PR TITLE
Fix fast actionclients with a patch

### PR DESCRIPTION
**Pull request by Timple**
Temporary workaround to mitigate:  https://github.com/ros2/rclpy/issues/1123

### CODE REVIEW

**Comment by MCFurry** [comment]
Why do we not simply take the changes from the open PR?

**Comment by Timple** [comment]
Since that means running a fork of `rclpy` because you need to modify `ActionClient` itself.
By wrapping it we can be one layer more up. As recommended in the issue thread.

And since is already under our fork, this was easiest.

I cannot (easily) solve this in our codebase as I then need to re-implement `SimpleActionState` again.

**Comment by MCFurry** [comment]
Aha, smart!

**Comment by MCFurry** [comment]
I'm not a reviewer btw, so I can't click "approve" ;-)

**Pull request merged**
